### ISSUE TITLE
Can others decrypt and know the real code ?!

### ISSUE THREAD

**Issue by eArabic** [ramdannur/EncodeScript#1]
Hello dear friend
Thank you very much for this very excellent script.
I have a simple question: Can others decrypt and know the real code, but it is not possible decryption.
I am a newbie in programming and sorry for mistakes in English. I only know Arabic.
Greetings and thank you very much

**Comment by ramdannur** [comment]
People can decode the script, but he needs to decode the script in the same way (same encryption) and he needs the key.
Some scripts still need to be developed again, maybe i will do next time.

**Comment by eArabic** [comment]
Dear Friend
Thanks for your quick response.
I am waiting for any update.
Thank you so much

**Comment by ramdannur** [comment]
You’re welcome
